### ISSUE TITLE
Audio in command line mode

### ISSUE THREAD

**Issue by Naheel-Azawy** [nrootconauto/Aiwnios#8]
Hello,

Running a file that calls the `Play()` function doesn't seem to be working in the command line mode.
Is this possible to achieve somehow?

Thanks

**Comment by Naheel-Azawy** [comment]
It looks like this is because sound is not initialized when `arg_cmd_line` is enabled.
I slightly modified the ending of the main function
```c
  SDL_Init(SDL_INIT_TIMER);
  SDL_Init(SDL_INIT_EVENTS);
  InitSound();
  if (!arg_cmd_line->count) {
    user_ev_num = SDL_RegisterEvents(1);
    SpawnCore(&Boot, NULL, 0);
    InputLoop(&quit);
    for (idx = 0; idx != mp_cnt(); idx++)
      __ShutdownCore(idx);
  } else {
    Boot();
  }
  SDL_Quit();
  arg_freetable(argtable, sizeof(argtable) / sizeof(*argtable));
  return EXIT_SUCCESS;
```

But I'm not sure, was there a reason sound is not initialized in command line?

**Comment by 1fishe2fishe** [comment]
used S8 as U8 would interfere with normal audio. thanks for reminding me to [fix mine too](https://github.com/1fishe2fishe/EXODUS/commit/308461f33bc44c2b684c850200e8bc6913051291)
